"""empty message

Revision ID: 66b132e7e7d4
Revises: a749f2af45bf
Create Date: 2024-01-16 18:24:43.683034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b132e7e7d4'
down_revision = 'a749f2af45bf'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_title', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('job_title')

    # ### end Alembic commands ###
