"""empty message

Revision ID: a749f2af45bf
Revises: c2310e3c873f
Create Date: 2024-01-16 07:46:46.293387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a749f2af45bf'
down_revision = 'c2310e3c873f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('job_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_title', sa.VARCHAR(length=255), server_default=sa.text("('')"), nullable=False))

    # ### end Alembic commands ###
