"""empty message

Revision ID: c2310e3c873f
Revises: 6050018b6569
Create Date: 2024-01-16 07:28:06.867811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2310e3c873f'
down_revision = '6050018b6569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_title', sa.String(length=255), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('linkedin', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('linkedin')
        batch_op.drop_column('job_title')

    # ### end Alembic commands ###
