"""empty message

Revision ID: fd3f4f59db8c
Revises: 66b132e7e7d4
Create Date: 2024-01-16 19:59:54.815056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd3f4f59db8c'
down_revision = '66b132e7e7d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('job_title')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=127),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=127),
               existing_nullable=True)

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_title', sa.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('job_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
